'use client';

import Link from 'next/link';
import { useTranslation } from '@/lib/i18n';

export default function AboutPage() {
  const { t } = useTranslation();
  const advantages = [[t('about.reliable.title'), t('about.reliable.desc'), '资料归档'], [t('about.efficient.title'), t('about.efficient.desc'), '快速检索'], [t('about.complete.title'), t('about.complete.desc'), '受控获取'], [t('about.community.title'), t('about.community.desc'), '持续维护']];
  return <main className="min-h-screen bg-[#f5f9fd]"><section className="relative overflow-hidden border-b border-slate-200 bg-[#eaf5ff] bg-cover bg-center" style={{ backgroundImage: "linear-gradient(90deg, rgba(234,245,255,0.98) 0%, rgba(234,245,255,0.9) 48%, rgba(234,245,255,0.3) 100%), url('/images/archive-atmosphere-v1.png')" }}><div className="absolute -right-12 -top-20 h-64 w-64 rounded-full border-[28px] border-white/35" /><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><nav className="flex items-center gap-2 text-sm text-slate-500"><Link href="/" className="hover:text-sky-700">{t('nav.home')}</Link><span>/</span><span>{t('nav.about')}</span></nav><p className="mt-8 text-xs font-bold tracking-[0.18em] text-sky-700">ABOUT STANDARD LIBRARY</p><h1 className="mt-2 text-3xl font-bold text-[#17324d]">{t('about.title')}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t('about.subtitle')}</p></div></section><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><section className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><p className="text-xs font-bold tracking-[0.16em] text-sky-700">WHY THIS PLATFORM</p><h2 className="mt-2 text-2xl font-bold text-slate-800">{t('about.intro')}</h2><div className="mt-5 max-w-3xl space-y-4 leading-7 text-slate-600"><p>{t('about.introText1')}</p><p>{t('about.introText2')}</p></div></section><section className="mt-10"><p className="text-xs font-bold tracking-[0.16em] text-sky-700">PLATFORM CAPABILITY</p><h2 className="mt-2 text-2xl font-bold text-slate-800">{t('about.advantages')}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{advantages.map(([title, description, label], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-200 hover:shadow-md"><span className="text-xs font-bold tracking-[0.15em] text-sky-700">0{index + 1} / {label}</span><h3 className="mt-5 text-lg font-bold text-slate-800">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>)}</div></section><section className="mt-10 rounded-2xl bg-[#17324d] p-7 text-white"><p className="text-xs font-bold tracking-[0.16em] text-sky-200">CONTACT</p><h2 className="mt-2 text-2xl font-bold">{t('about.contact')}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{t('about.contactText')}</p><div className="mt-6 grid gap-3 text-sm text-slate-200 sm:grid-cols-2"><div className="rounded-xl bg-white/10 p-4">{t('about.email')}</div><div className="rounded-xl bg-white/10 p-4">{t('about.address')}</div></div></section></div></main>;
}
